package edu.udistrital.espingsw.liquidacionproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Estudiante implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String noDocumento;

   private java.lang.String nombres;

   private java.lang.String apellidos;

   @org.kie.api.definition.type.Description("Puntos B\u00E1sicos de Matricula")
   private edu.udistrital.espingsw.liquidacionproject.PuntosBasicosMatricula pbm;

   @org.kie.api.definition.type.Description(value = "Pensi\u00F3n del \u00FAltimo a\u00F1o de bachillerato (en salarios m\u00EDnimos)")
   private java.lang.Double pension;

   @org.kie.api.definition.type.Description(value = "Ingresos Brutos Familiares (en salarios m\u00EDnimos)")
   private java.lang.Double ingresosFamiliares;

   private edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaEstudiante;

   private edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaRespManutencion;

   @org.kie.api.definition.type.Description(value = "TRUE en caso de que los padres del estudiante residen fuera del perimetro urbano")
   private java.lang.Boolean isPadresFueraPerim;

   private java.lang.Boolean viveSolo;

   private java.lang.String estadoCivil;

   private java.lang.Boolean isTrabaja;

   public Estudiante()
   {

   }

   public java.lang.String getNoDocumento()
   {
      return this.noDocumento;
   }

   public void setNoDocumento(java.lang.String noDocumento)
   {
      this.noDocumento = noDocumento;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public java.lang.String getApellidos()
   {
      return this.apellidos;
   }

   public void setApellidos(java.lang.String apellidos)
   {
      this.apellidos = apellidos;
   }

   public edu.udistrital.espingsw.liquidacionproject.PuntosBasicosMatricula getPbm()
   {
      return this.pbm;
   }

   public void setPbm(
         edu.udistrital.espingsw.liquidacionproject.PuntosBasicosMatricula pbm)
   {
      this.pbm = pbm;
   }

   public java.lang.Double getPension()
   {
      return this.pension;
   }

   public void setPension(java.lang.Double pension)
   {
      this.pension = pension;
   }

   public java.lang.Double getIngresosFamiliares()
   {
      return this.ingresosFamiliares;
   }

   public void setIngresosFamiliares(java.lang.Double ingresosFamiliares)
   {
      this.ingresosFamiliares = ingresosFamiliares;
   }

   public edu.udistrital.espingsw.liquidacionproject.LugarResidencia getResidenciaEstudiante()
   {
      return this.residenciaEstudiante;
   }

   public void setResidenciaEstudiante(
         edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaEstudiante)
   {
      this.residenciaEstudiante = residenciaEstudiante;
   }

   public edu.udistrital.espingsw.liquidacionproject.LugarResidencia getResidenciaRespManutencion()
   {
      return this.residenciaRespManutencion;
   }

   public void setResidenciaRespManutencion(
         edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaRespManutencion)
   {
      this.residenciaRespManutencion = residenciaRespManutencion;
   }

   public java.lang.Boolean getIsPadresFueraPerim()
   {
      return this.isPadresFueraPerim;
   }

   public void setIsPadresFueraPerim(java.lang.Boolean isPadresFueraPerim)
   {
      this.isPadresFueraPerim = isPadresFueraPerim;
   }

   public java.lang.Boolean getViveSolo()
   {
      return this.viveSolo;
   }

   public void setViveSolo(java.lang.Boolean viveSolo)
   {
      this.viveSolo = viveSolo;
   }

   public java.lang.String getEstadoCivil()
   {
      return this.estadoCivil;
   }

   public void setEstadoCivil(java.lang.String estadoCivil)
   {
      this.estadoCivil = estadoCivil;
   }

   public java.lang.Boolean getIsTrabaja()
   {
      return this.isTrabaja;
   }

   public void setIsTrabaja(java.lang.Boolean isTrabaja)
   {
      this.isTrabaja = isTrabaja;
   }

   public Estudiante(
         java.lang.String noDocumento,
         java.lang.String nombres,
         java.lang.String apellidos,
         edu.udistrital.espingsw.liquidacionproject.PuntosBasicosMatricula pbm,
         java.lang.Double pension,
         java.lang.Double ingresosFamiliares,
         edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaEstudiante,
         edu.udistrital.espingsw.liquidacionproject.LugarResidencia residenciaRespManutencion,
         java.lang.Boolean isPadresFueraPerim, java.lang.Boolean viveSolo,
         java.lang.String estadoCivil, java.lang.Boolean isTrabaja)
   {
      this.noDocumento = noDocumento;
      this.nombres = nombres;
      this.apellidos = apellidos;
      this.pbm = pbm;
      this.pension = pension;
      this.ingresosFamiliares = ingresosFamiliares;
      this.residenciaEstudiante = residenciaEstudiante;
      this.residenciaRespManutencion = residenciaRespManutencion;
      this.isPadresFueraPerim = isPadresFueraPerim;
      this.viveSolo = viveSolo;
      this.estadoCivil = estadoCivil;
      this.isTrabaja = isTrabaja;
   }

}