package edu.udistrital.espingsw.liquidacionproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LugarResidencia implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer estrato;

   private java.lang.String nombreCiudad;

   private java.lang.Integer noHabitantesCiudad;

   private java.lang.Boolean isAreaRural;

   private java.lang.Boolean hasServiciosEstratificados;

   public LugarResidencia()
   {
   }

   public java.lang.Integer getEstrato()
   {
      return this.estrato;
   }

   public void setEstrato(java.lang.Integer estrato)
   {
      this.estrato = estrato;
   }

   public java.lang.String getNombreCiudad()
   {
      return this.nombreCiudad;
   }

   public void setNombreCiudad(java.lang.String nombreCiudad)
   {
      this.nombreCiudad = nombreCiudad;
   }

   public java.lang.Integer getNoHabitantesCiudad()
   {
      return this.noHabitantesCiudad;
   }

   public void setNoHabitantesCiudad(java.lang.Integer noHabitantesCiudad)
   {
      this.noHabitantesCiudad = noHabitantesCiudad;
   }

   public java.lang.Boolean getIsAreaRural()
   {
      return this.isAreaRural;
   }

   public void setIsAreaRural(java.lang.Boolean isAreaRural)
   {
      this.isAreaRural = isAreaRural;
   }

   public java.lang.Boolean getHasServiciosEstratificados()
   {
      return this.hasServiciosEstratificados;
   }

   public void setHasServiciosEstratificados(
         java.lang.Boolean hasServiciosEstratificados)
   {
      this.hasServiciosEstratificados = hasServiciosEstratificados;
   }

   public LugarResidencia(java.lang.Integer estrato,
         java.lang.String nombreCiudad, java.lang.Integer noHabitantesCiudad,
         java.lang.Boolean isAreaRural,
         java.lang.Boolean hasServiciosEstratificados)
   {
      this.estrato = estrato;
      this.nombreCiudad = nombreCiudad;
      this.noHabitantesCiudad = noHabitantesCiudad;
      this.isAreaRural = isAreaRural;
      this.hasServiciosEstratificados = hasServiciosEstratificados;
   }

}