package edu.udistrital.espingsw.liquidacionproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PuntosBasicosMatricula implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer a1;

   private java.lang.Integer a2;

   private java.lang.Integer a3;

   private Double b1;

   private Double b2;

   private Double b3;

   private Double b4;

   public PuntosBasicosMatricula()
   {
      this.a1 = 100;
   }

   public java.lang.Integer getA1()
   {
      return this.a1;
   }

   public void setA1(java.lang.Integer a1)
   {
      this.a1 = a1;
   }

   public java.lang.Integer getA2()
   {
      return this.a2;
   }

   public void setA2(java.lang.Integer a2)
   {
      this.a2 = a2;
   }

   public java.lang.Integer getA3()
   {
      return this.a3;
   }

   public void setA3(java.lang.Integer a3)
   {
      this.a3 = a3;
   }

   public java.lang.Double getB1()
   {
      return this.b1;
   }

   public void setB1(java.lang.Double b1)
   {
      this.b1 = b1;
   }

   public java.lang.Double getB3()
   {
      return this.b3;
   }

   public void setB3(java.lang.Double b3)
   {
      this.b3 = b3;
   }

   public java.lang.Double getB2()
   {
      return this.b2;
   }

   public void setB2(java.lang.Double b2)
   {
      this.b2 = b2;
   }

   public java.lang.Double getB4()
   {
      return this.b4;
   }

   public void setB4(java.lang.Double b4)
   {
      this.b4 = b4;
   }

   public PuntosBasicosMatricula(java.lang.Integer a1, java.lang.Integer a2,
         java.lang.Integer a3, java.lang.Double b1, java.lang.Double b2,
         java.lang.Double b3, java.lang.Double b4)
   {
      this.a1 = a1;
      this.a2 = a2;
      this.a3 = a3;
      this.b1 = b1;
      this.b2 = b2;
      this.b3 = b3;
      this.b4 = b4;
   }

}